version: '3.8'

services:
  node-app-hokusai:
    container_name: hokusai-api
    build: .
    image: hokusai-api
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/hokusai-api
    networks:
      - hokusai-network

networks:
  hokusai-network:
    driver: bridge
